In [1]:
import numpy as np

In [2]:
# create the  1-D array

arr_1d =  np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [4]:
# two 2d Data 

arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# create the 3D arrya

arr_3d = np.array([[[1,2,3],[4,5,6],[12,3,5]]])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [12,  3,  5]]])

In [12]:
# create the 4D  array

arr_4d = np.array([[[[1,2,3,4],[2,3,4,5],[3,42,2,5]]]])
arr_4d



array([[[[ 1,  2,  3,  4],
         [ 2,  3,  4,  5],
         [ 3, 42,  2,  5]]]])

In [13]:

arr_1d =  np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [14]:
# 1d slice syntax:  arr[start:stop:step]

arr_1d[1:3]

array([2, 3])

In [15]:
arr_2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,8,7,6]])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [18]:
# syntax 2d : arr[row_start:rows_stop,col_start:col_stop]

arr_2d[1:,1:3]

array([[6, 7],
       [8, 7]])

In [19]:
arr_3d = np.array([[[1,2,3,4],
                   [3,4,5,6],
                   [5,6,3,4],
                   [4,5,5,6]]])

arr_3d

array([[[1, 2, 3, 4],
        [3, 4, 5, 6],
        [5, 6, 3, 4],
        [4, 5, 5, 6]]])

In [20]:
arr_3d[0,1:,:3]


array([[3, 4, 5],
       [5, 6, 3],
       [4, 5, 5]])

In [22]:
arr_3d = np.array([
                    [
                      [1,2,3,4],
                      [3,4,5,6],
                      [5,6,3,4],
                      [4,5,5,6]
                   ],
                   [
                      [1,2,3,4],
                      [3,4,5,6],
                      [5,6,3,4],
                      [4,5,5,6]
                   ]    
                  ])

arr_3d[0,1:3,1:3]

array([[4, 5],
       [6, 3]])

In [23]:
arr_4d = np.array(

    [
        [
            [
                [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]
            ],
            [
                [10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]
            ]
        ]
    ]
)

arr_4d[0,1,1:,0:2]

array([[13, 14],
       [16, 17]])

In [26]:
# check the diamenstion
arr_2d.ndim

2

In [29]:
# Array of Zeros

arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
# array of ones

arr = np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
#  Create Identity Matrix 
arr = np.eye(5)
arr


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
# create the range using : arange()

arr_range =  np.arange(2,15,2)
arr_range

array([ 2,  4,  6,  8, 10, 12, 14])

In [8]:
# create the linspace()

lin_space = np.linspace(0,1,10)
lin_space

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
# create the random array

array = np.random.rand(10,4)


In [53]:
# create the random integer array

age = np.random.randint(20,30,100)
np.sort(age)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25,
       25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
       27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
       28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29])

In [ ]:
list1 = [1,2,3,34,5,5]
array = np.array(list1)

In [24]:
array = np.array([[1,2,3,4],
                 [2,3,4,5]])

array

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [26]:
# method 1 : shape

array.shape

(2, 4)

In [28]:
# check the diamenstion of array

# method 2: ndim
array.ndim

2

In [29]:
# check the dtype of value
# method 3:dtype

array.dtype

dtype('int32')

In [34]:
# check memory of array

array.nbytes

32

In [37]:
# Transpose of array 

array.T

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [38]:
# create the complex number
a = np.array([1+2j, 3+4j]) 

a.real

array([1., 3.])

In [39]:
a.imag

array([2., 4.])

In [43]:
array

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [45]:
array.sum(axis= 1)

array([10, 14])

In [52]:
# 4. reshape() 
#Changes shape of array. 
a = np.array([1,2,3,4,5,6])

a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
name  = ['Male','Female']

Gender = np.random.choice(name,100)
Gender

array(['Male', 'Female', 'Female', 'Female', 'Female', 'Female', 'Male',
       'Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Female', 'Female', 'Male', 'Male', 'Male', 'Female',
       'Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female',
       'Female', 'Female', 'Female', 'Male', 'Male', 'Male', 'Female',
       'Female', 'Female', 'Male', 'Male', 'Male', 'Male', 'Female',
       'Female', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female',
       'Female', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female',
       'Male', 'Female', 'Male', 'Male', 'Male', 'Female', 'Female',
       'Female', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female',
       'Female', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female',
       'Male', 'Female', 'Female', 'Male', 'Male', 'Male', 'Female',
       'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male', 'Male',
       'Female', 'Female', 'Female', 'Male', 'Female', 'Female', 'Male',
    

In [58]:
# generate the float value 

Salary = np.random.uniform(10000,25000,100)
np.round(Salary,2)

array([20510.28, 17247.06, 22671.18, 11633.49, 14817.04, 14119.58,
       18756.44, 10883.14, 23002.13, 17255.31, 17019.99, 22823.56,
       13882.42, 17084.24, 13139.65, 18449.52, 21534.55, 20040.25,
       14392.63, 20586.49, 16270.09, 20263.84, 24080.42, 20094.01,
       15642.01, 17213.68, 18196.19, 11984.73, 14605.57, 15641.08,
       10730.47, 21588.24, 15531.98, 23603.15, 17075.87, 13544.37,
       10865.61, 24441.17, 11575.22, 16133.1 , 17225.47, 23619.06,
       24002.61, 22642.43, 19572.41, 17957.26, 14898.12, 18253.91,
       23029.72, 16369.  , 10148.95, 17142.51, 24533.95, 20354.72,
       12898.68, 19459.73, 24987.67, 23308.31, 19517.43, 23396.1 ,
       23634.92, 14504.63, 17887.99, 19257.79, 14668.31, 21946.47,
       11762.4 , 24407.52, 15802.48, 14467.76, 10337.2 , 10717.69,
       23604.65, 17649.82, 22103.18, 12256.92, 24430.11, 23992.46,
       12434.72, 13554.2 , 23937.81, 15729.15, 16744.15, 19709.6 ,
       16791.87, 23982.53, 16716.39, 24021.54, 22316.18, 22912

In [60]:
Age = np.random.randint(20,30,100)
Age

array([23, 21, 27, 28, 22, 26, 23, 28, 29, 22, 29, 28, 27, 20, 25, 27, 23,
       29, 26, 29, 28, 25, 22, 25, 23, 21, 24, 26, 21, 21, 27, 28, 23, 27,
       23, 20, 21, 23, 23, 29, 28, 24, 28, 27, 22, 21, 20, 20, 27, 29, 24,
       24, 23, 28, 23, 21, 20, 20, 22, 21, 23, 27, 29, 27, 20, 20, 28, 28,
       25, 26, 29, 20, 27, 29, 26, 27, 20, 23, 25, 21, 20, 21, 26, 24, 26,
       27, 28, 22, 28, 29, 20, 22, 24, 24, 20, 20, 27, 29, 27, 20])

In [99]:
# id  : 100
# Name 
# Gender
# Dept
# Exp
# Role 
# Salary


# ID 
ID =  np.arange(100,200)



# name :

name = ["Sumit","Vaishnavi","Ayushi","Sameer","Sahil","Neha","Rahul","Danish","Sitara","Haritha","Akshitha"]

Name = np.random.choice(name,100)


# gender

g = ["Male","Female"]
Gender =  np.random.choice(g,100)

# dept

dept= ["IT","Finace","HR","Inventory","Call Center","Science"]

Dept = np.random.choice(dept,100)

# Exp 

exp = np.random.uniform(1,20,100)
exp = np.round(exp,1)
exp

# role

role = ["Devloper","Testing","Data Scientist","AI Engineer","Devops"]

Role = np.random.choice(role,100)

# salary

salary = np.random.uniform(45000, 100000,100)
salary = np.round(salary,2)
 
len(salaru)

100

In [101]:
import pandas as pd
df = pd.DataFrame({
    "ID":ID,
    "Name":Name,
    "Gender":Gender,
    "Department":Dept,
    "Exp":exp,
    "Job Role":Role,
    "Salary":salary
})

In [103]:
df.head()

,ID,Name,Gender,Department,Exp,Job Role,Salary
0,100,Sahil,Male,Science,14.4,Data Scientist,81643.20
1,101,Haritha,Female,Call Center,9.5,Devloper,46372.71
2,102,Rahul,Male,Science,7.0,Devops,52120.70
3,103,Sahil,Male,Call Center,19.8,Data Scientist,88338.66
4,104,Sahil,Male,Inventory,16.5,Devloper,77339.06
